GET http://localhost:8888/v1/groups

###

GET http://localhost:8888/v1/groups/61b4427d8521a92aa5990cab

###

POST　http://localhost:8888/v1/groups
Content-Type: application/json

{
    "className": "21.12",
    "groupName": "Lion"
}

###

PUT　http://localhost:8888/v1/groups/61b4427d8521a92aa5990cab
Content-Type: application/json

{
    "className": "21.12"
}

###

DELETE http://localhost:8888/v1/groups/61b4427d8521a92aa5990cab